# Site Settings
title: Lola Collective
email: Lola@gmail.com
facebook: facebook
twitter: twitter
instagram: instagram
spotify: spotify

baseurl: "/LolaCommerce"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: /LolaCommerce/assets/css
  style: :nested